name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cached_network_image: ^3.2.0
  animated_text_kit: ^4.2.1
  modal_progress_hud: ^0.1.3
  flutter_native_splash: ^1.2.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.5
  firebase_messaging: ^10.0.8
  google_sign_in: ^5.1.1

  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+2
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.0
  photo_view: ^0.13.0
  provider: ^6.0.1
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/


